function DistFeatures = ExtractDistanceFeatures(OtherFeatures)
    DistFeatures = zeros(8,size(OtherFeatures,2));
    DistFeatures(1,:) = sqrt( (OtherFeatures(5,:).^2) + ...
        (OtherFeatures(17,:).^2));% PQ dist
    DistFeatures(2,:) = sqrt( (OtherFeatures(2,:).^2) + ...
        (OtherFeatures(18,:).^2));% QR dist
    DistFeatures(3,:) = sqrt( (OtherFeatures(3,:).^2) + ...
        (OtherFeatures(19,:).^2));% RS dist
    DistFeatures(4,:) = sqrt( (OtherFeatures(9,:).^2) + ...
        (OtherFeatures(20,:).^2));% ST dist
    DistFeatures(5,:) = sqrt( (OtherFeatures(7,:).^2) + ...
        (OtherFeatures(21,:).^2));% QS dist
    DistFeatures(6,:) = sqrt( (OtherFeatures(1,:).^2) + ...
        (OtherFeatures(13,:).^2));% PR dist
    DistFeatures(7,:) = DistFeatures(4,:)./DistFeatures(5,:); % ST/QS
    DistFeatures(8,:) = DistFeatures(3,:)./DistFeatures(2,:); % RS/QR
end